application: 22download202
version: 1-0-test
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /clearcache
  script: clearcache.py
  
- url: /favicon.ico
  static_files: stylesheets/favicon.ico
  upload: stylesheets/favicon.ico

- url: .*
  script: html.py
