application: 22download202
version: 1-0-test
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /22tracks\.txt
  script: text.py

- url: /22tracks\.json
  script: json.py

- url: /clearcache
  script: clearcache.py

- url: .*
  script: html.py
